### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by fbc** [Unbihexium/hackintosh#1]
Do I just rename the EFI folder in the EFI partition and put this one in it's place?
I already tried that and I just get a blinking dot in the upper right had corner.
How do I gen the SMBIOS portions? I suppose that is what is wrong.

**Comment by Unbihexium** [comment]
To understand how to build hackintosh go to https://dortania.github.io/ and https://reddit.com/r/hackintosh/ and read guides.
